# Generated by Django 4.2.6 on 2023-10-14 06:39

import datetime

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('rko', models.BooleanField(default=False)),
                ('has_ramp', models.BooleanField(default=False)),
                ('office_type', models.CharField(max_length=255)),
                ('sale_point_format', models.CharField(max_length=255)),
                ('suo_availability', models.BooleanField(default=False)),
                ('kep', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('пн', 'пн'), ('вт', 'вт'), ('ср', 'ср'), ('чт', 'чт'), ('пт', 'пт'), ('сб', 'сб'), ('вс', 'вс')], max_length=2, null=True)),
                ('opening_time', models.TimeField(blank=True, choices=[(datetime.time(0, 0), 'T0000_0015'), (datetime.time(0, 15), 'T0015_0030'), (datetime.time(0, 30), 'T0030_0045'), (datetime.time(0, 45), 'T0045_0100'), (datetime.time(1, 0), 'T0100_0115'), (datetime.time(1, 15), 'T0115_0130'), (datetime.time(1, 30), 'T0130_0145'), (datetime.time(1, 45), 'T0145_0200'), (datetime.time(2, 0), 'T0200_0215'), (datetime.time(2, 15), 'T0215_0230'), (datetime.time(2, 30), 'T0230_0245'), (datetime.time(2, 45), 'T0245_0300'), (datetime.time(3, 0), 'T0300_0315'), (datetime.time(3, 15), 'T0315_0330'), (datetime.time(3, 30), 'T0330_0345'), (datetime.time(3, 45), 'T0345_0400'), (datetime.time(4, 0), 'T0400_0415'), (datetime.time(4, 15), 'T0415_0430'), (datetime.time(4, 30), 'T0430_0445'), (datetime.time(4, 45), 'T0445_0500'), (datetime.time(5, 0), 'T0500_0515'), (datetime.time(5, 15), 'T0515_0530'), (datetime.time(5, 30), 'T0530_0545'), (datetime.time(5, 45), 'T0545_0600'), (datetime.time(6, 0), 'T0600_0615'), (datetime.time(6, 15), 'T0615_0630'), (datetime.time(6, 30), 'T0630_0645'), (datetime.time(6, 45), 'T0645_0700'), (datetime.time(7, 0), 'T0700_0715'), (datetime.time(7, 15), 'T0715_0730'), (datetime.time(7, 30), 'T0730_0745'), (datetime.time(7, 45), 'T0745_0800'), (datetime.time(8, 0), 'T0800_0815'), (datetime.time(8, 15), 'T0815_0830'), (datetime.time(8, 30), 'T0830_0845'), (datetime.time(8, 45), 'T0845_0900'), (datetime.time(9, 0), 'T0900_0915'), (datetime.time(9, 15), 'T0915_0930'), (datetime.time(9, 30), 'T0930_0945'), (datetime.time(9, 45), 'T0945_1000'), (datetime.time(10, 0), 'T1000_1015'), (datetime.time(10, 15), 'T1015_1030'), (datetime.time(10, 30), 'T1030_1045'), (datetime.time(10, 45), 'T1045_1100'), (datetime.time(11, 0), 'T1100_1115'), (datetime.time(11, 15), 'T1115_1130'), (datetime.time(11, 30), 'T1130_1145'), (datetime.time(11, 45), 'T1145_1200'), (datetime.time(12, 0), 'T1200_1215'), (datetime.time(12, 15), 'T1215_1230'), (datetime.time(12, 30), 'T1230_1245'), (datetime.time(12, 45), 'T1245_1300'), (datetime.time(13, 0), 'T1300_1315'), (datetime.time(13, 15), 'T1315_1330'), (datetime.time(13, 30), 'T1330_1345'), (datetime.time(13, 45), 'T1345_1400'), (datetime.time(14, 0), 'T1400_1415'), (datetime.time(14, 15), 'T1415_1430'), (datetime.time(14, 30), 'T1430_1445'), (datetime.time(14, 45), 'T1445_1500'), (datetime.time(15, 0), 'T1500_1515'), (datetime.time(15, 15), 'T1515_1530'), (datetime.time(15, 30), 'T1530_1545'), (datetime.time(15, 45), 'T1545_1600'), (datetime.time(16, 0), 'T1600_1615'), (datetime.time(16, 15), 'T1615_1630'), (datetime.time(16, 30), 'T1630_1645'), (datetime.time(16, 45), 'T1645_1700'), (datetime.time(17, 0), 'T1700_1715'), (datetime.time(17, 15), 'T1715_1730'), (datetime.time(17, 30), 'T1730_1745'), (datetime.time(17, 45), 'T1745_1800'), (datetime.time(18, 0), 'T1800_1815'), (datetime.time(18, 15), 'T1815_1830'), (datetime.time(18, 30), 'T1830_1845'), (datetime.time(18, 45), 'T1845_1900'), (datetime.time(19, 0), 'T1900_1915'), (datetime.time(19, 15), 'T1915_1930'), (datetime.time(19, 30), 'T1930_1945'), (datetime.time(19, 45), 'T1945_2000'), (datetime.time(20, 0), 'T2000_2015'), (datetime.time(20, 15), 'T2015_2030'), (datetime.time(20, 30), 'T2030_2045'), (datetime.time(20, 45), 'T2045_2100'), (datetime.time(21, 0), 'T2100_2115'), (datetime.time(21, 15), 'T2115_2130'), (datetime.time(21, 30), 'T2130_2145'), (datetime.time(21, 45), 'T2145_2200'), (datetime.time(22, 0), 'T2200_2215'), (datetime.time(22, 15), 'T2215_2230'), (datetime.time(22, 30), 'T2230_2245'), (datetime.time(22, 45), 'T2245_2300'), (datetime.time(23, 0), 'T2300_2315'), (datetime.time(23, 15), 'T2315_2330'), (datetime.time(23, 30), 'T2330_2345'), (datetime.time(23, 45), 'T2345_0000')], null=True)),
                ('closing_time', models.TimeField(blank=True, choices=[(datetime.time(0, 15), 'T0000_0015'), (datetime.time(0, 30), 'T0015_0030'), (datetime.time(0, 45), 'T0030_0045'), (datetime.time(1, 0), 'T0045_0100'), (datetime.time(1, 15), 'T0100_0115'), (datetime.time(1, 30), 'T0115_0130'), (datetime.time(1, 45), 'T0130_0145'), (datetime.time(2, 0), 'T0145_0200'), (datetime.time(2, 15), 'T0200_0215'), (datetime.time(2, 30), 'T0215_0230'), (datetime.time(2, 45), 'T0230_0245'), (datetime.time(3, 0), 'T0245_0300'), (datetime.time(3, 15), 'T0300_0315'), (datetime.time(3, 30), 'T0315_0330'), (datetime.time(3, 45), 'T0330_0345'), (datetime.time(4, 0), 'T0345_0400'), (datetime.time(4, 15), 'T0400_0415'), (datetime.time(4, 30), 'T0415_0430'), (datetime.time(4, 45), 'T0430_0445'), (datetime.time(5, 0), 'T0445_0500'), (datetime.time(5, 15), 'T0500_0515'), (datetime.time(5, 30), 'T0515_0530'), (datetime.time(5, 45), 'T0530_0545'), (datetime.time(6, 0), 'T0545_0600'), (datetime.time(6, 15), 'T0600_0615'), (datetime.time(6, 30), 'T0615_0630'), (datetime.time(6, 45), 'T0630_0645'), (datetime.time(7, 0), 'T0645_0700'), (datetime.time(7, 15), 'T0700_0715'), (datetime.time(7, 30), 'T0715_0730'), (datetime.time(7, 45), 'T0730_0745'), (datetime.time(8, 0), 'T0745_0800'), (datetime.time(8, 15), 'T0800_0815'), (datetime.time(8, 30), 'T0815_0830'), (datetime.time(8, 45), 'T0830_0845'), (datetime.time(9, 0), 'T0845_0900'), (datetime.time(9, 15), 'T0900_0915'), (datetime.time(9, 30), 'T0915_0930'), (datetime.time(9, 45), 'T0930_0945'), (datetime.time(10, 0), 'T0945_1000'), (datetime.time(10, 15), 'T1000_1015'), (datetime.time(10, 30), 'T1015_1030'), (datetime.time(10, 45), 'T1030_1045'), (datetime.time(11, 0), 'T1045_1100'), (datetime.time(11, 15), 'T1100_1115'), (datetime.time(11, 30), 'T1115_1130'), (datetime.time(11, 45), 'T1130_1145'), (datetime.time(12, 0), 'T1145_1200'), (datetime.time(12, 15), 'T1200_1215'), (datetime.time(12, 30), 'T1215_1230'), (datetime.time(12, 45), 'T1230_1245'), (datetime.time(13, 0), 'T1245_1300'), (datetime.time(13, 15), 'T1300_1315'), (datetime.time(13, 30), 'T1315_1330'), (datetime.time(13, 45), 'T1330_1345'), (datetime.time(14, 0), 'T1345_1400'), (datetime.time(14, 15), 'T1400_1415'), (datetime.time(14, 30), 'T1415_1430'), (datetime.time(14, 45), 'T1430_1445'), (datetime.time(15, 0), 'T1445_1500'), (datetime.time(15, 15), 'T1500_1515'), (datetime.time(15, 30), 'T1515_1530'), (datetime.time(15, 45), 'T1530_1545'), (datetime.time(16, 0), 'T1545_1600'), (datetime.time(16, 15), 'T1600_1615'), (datetime.time(16, 30), 'T1615_1630'), (datetime.time(16, 45), 'T1630_1645'), (datetime.time(17, 0), 'T1645_1700'), (datetime.time(17, 15), 'T1700_1715'), (datetime.time(17, 30), 'T1715_1730'), (datetime.time(17, 45), 'T1730_1745'), (datetime.time(18, 0), 'T1745_1800'), (datetime.time(18, 15), 'T1800_1815'), (datetime.time(18, 30), 'T1815_1830'), (datetime.time(18, 45), 'T1830_1845'), (datetime.time(19, 0), 'T1845_1900'), (datetime.time(19, 15), 'T1900_1915'), (datetime.time(19, 30), 'T1915_1930'), (datetime.time(19, 45), 'T1930_1945'), (datetime.time(20, 0), 'T1945_2000'), (datetime.time(20, 15), 'T2000_2015'), (datetime.time(20, 30), 'T2015_2030'), (datetime.time(20, 45), 'T2030_2045'), (datetime.time(21, 0), 'T2045_2100'), (datetime.time(21, 15), 'T2100_2115'), (datetime.time(21, 30), 'T2115_2130'), (datetime.time(21, 45), 'T2130_2145'), (datetime.time(22, 0), 'T2145_2200'), (datetime.time(22, 15), 'T2200_2215'), (datetime.time(22, 30), 'T2215_2230'), (datetime.time(22, 45), 'T2230_2245'), (datetime.time(23, 0), 'T2245_2300'), (datetime.time(23, 15), 'T2300_2315'), (datetime.time(23, 30), 'T2315_2330'), (datetime.time(23, 45), 'T2330_2345'), (datetime.time(0, 0), 'T2345_0000')], null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('for_individuals', models.BooleanField(default=False)),
                ('for_legals', models.BooleanField(default=False)),
                ('is_break', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
        ),
    ]
